# ===========================================
# 勤怠管理システム メイン設定
# ===========================================

spring:
  application:
    name: kintai-system
  
  profiles:
    active: dev
  
  # データベース設定
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kintai_system?useSSL=false&serverTimezone=Asia/Tokyo&characterEncoding=utf8mb4&useUnicode=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  
  # JPA/Hibernate設定
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Tokyo
    open-in-view: false
  
  # セッション設定
  session:
    timeout: 600s
  
  # CORS設定
  web:
    cors:
      allowed-origins: 
        - http://localhost:3000
        - https://frontend-url
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

# サーバー設定
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

# セキュリティ設定
security:
  jwt:
    secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentOnlyChangeInProduction}
    expiration: 86400000 # 24時間（ミリ秒）

# JWT設定
jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentOnlyChangeInProduction}
  expiration: 600 # 10分 = 600秒

# ログ設定
logging:
  level:
    com.kintai: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# ===========================================
# 開発環境設定 (dev)
# ===========================================
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:mysql://localhost:3306/kintai_system_dev?useSSL=false&serverTimezone=Asia/Tokyo&characterEncoding=utf8mb4&useUnicode=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# 開発環境ログ設定
logging:
  level:
    com.kintai: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/kintai-dev.log

---
# ===========================================
# 本番環境設定 (prod)
# ===========================================
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:kintai_system}?useSSL=true&serverTimezone=Asia/Tokyo&characterEncoding=utf8mb4&useUnicode=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

# 本番環境ログ設定
logging:
  level:
    com.kintai: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: logs/kintai-prod.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB

---
# ===========================================
# Railway環境設定 (railway)
# ===========================================
spring:
  config:
    activate:
      on-profile: railway
  
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=true&serverTimezone=Asia/Tokyo&characterEncoding=utf8mb4&useUnicode=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

# Railway環境ログ設定
logging:
  level:
    com.kintai: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Railway環境サーバー設定
server:
  port: ${PORT:8080}
