server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/kintai_db?useSSL=false&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  session:
    store-type: jdbc
    timeout: 600s

logging:
  level:
    com.kintai: DEBUG
    org.springframework.security: DEBUG

kintai:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyForKintaiSystem2025}
    expiration: 600000

  fastapi:
    url: ${FASTAPI_URL:http://localhost:8081}